name: Rust

on: workflow_dispatch
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: sudo apt install libdbus-1-dev && cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload BUILD
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bluster_build
        path: .
